package tn.esprit.tic.civiAgora.mappers.organizationRequestMappers;

import org.springframework.stereotype.Component;
import tn.esprit.tic.civiAgora.dao.entity.OrganizationRequest;
import tn.esprit.tic.civiAgora.dto.organizationRequestDto.OrganizationRequestDto;

@Component
public class OrganizationRequestMapper {

    public OrganizationRequestDto toDto(OrganizationRequest request) {
        if (request == null) return null;
        return OrganizationRequestDto.builder()
                .id(request.getId())
                .organizationName(request.getOrganizationName())
                .desiredSlug(request.getDesiredSlug())
                .contactPersonName(request.getContactPersonName())
                .contactEmail(request.getContactEmail())
                .phone(request.getPhone())
                .address(request.getAddress())
                .description(request.getDescription())
                .logoUrl(request.getLogoUrl())
                .adminFirstName(request.getAdminFirstName())
                .adminLastName(request.getAdminLastName())
                .adminEmail(request.getAdminEmail())
                .expectedNumberOfUsers(request.getExpectedNumberOfUsers())
                .requestedModuleCodes(request.getRequestedModuleCodes())
                .requestedPrimaryColor(request.getRequestedPrimaryColor())
                .requestedSecondaryColor(request.getRequestedSecondaryColor())
                .brandingNotes(request.getBrandingNotes())
                .additionalNotes(request.getAdditionalNotes())
                .requestStatus(request.getRequestStatus())
                .quoteStatus(request.getQuoteStatus())
                .paymentStatus(request.getPaymentStatus())
                .publicVisibilityRequested(request.getPublicVisibilityRequested())
                .createdAt(request.getCreatedAt())
                .updatedAt(request.getUpdatedAt())
                .reviewedAt(request.getReviewedAt())
                .reviewComment(request.getReviewComment())
                .reviewedBy(request.getReviewedBy())
                .declineReason(request.getDeclineReason())
                .approvalNotes(request.getApprovalNotes())
                .processedBy(request.getProcessedBy())
                .quoteSentAt(request.getQuoteSentAt())
                .approvedAt(request.getApprovedAt())
                .declinedAt(request.getDeclinedAt())
                .paidAt(request.getPaidAt())
                .activatedAt(request.getActivatedAt())
                .quoteBaseFee(request.getQuoteBaseFee())
                .quoteUserFee(request.getQuoteUserFee())
                .quoteModuleFee(request.getQuoteModuleFee())
                .quoteSetupFee(request.getQuoteSetupFee())
                .quoteTotal(request.getQuoteTotal())
                .quoteAssumptions(request.getQuoteAssumptions())
                .quoteAxesSnapshot(request.getQuoteAxesSnapshot())
                .organizationCreatedId(request.getOrganizationCreatedId())
                .build();
    }

    public OrganizationRequest toEntity(OrganizationRequestDto requestDto) {
        if (requestDto == null) return null;
        return OrganizationRequest.builder()
                .id(requestDto.getId())
                .organizationName(requestDto.getOrganizationName())
                .desiredSlug(requestDto.getDesiredSlug())
                .contactPersonName(requestDto.getContactPersonName())
                .contactEmail(requestDto.getContactEmail())
                .phone(requestDto.getPhone())
                .address(requestDto.getAddress())
                .description(requestDto.getDescription())
                .logoUrl(requestDto.getLogoUrl())
                .adminFirstName(requestDto.getAdminFirstName())
                .adminLastName(requestDto.getAdminLastName())
                .adminEmail(requestDto.getAdminEmail())
                .expectedNumberOfUsers(requestDto.getExpectedNumberOfUsers())
                .requestedModuleCodes(requestDto.getRequestedModuleCodes())
                .requestedPrimaryColor(requestDto.getRequestedPrimaryColor())
                .requestedSecondaryColor(requestDto.getRequestedSecondaryColor())
                .brandingNotes(requestDto.getBrandingNotes())
                .additionalNotes(requestDto.getAdditionalNotes())
                .requestStatus(requestDto.getRequestStatus())
                .quoteStatus(requestDto.getQuoteStatus())
                .paymentStatus(requestDto.getPaymentStatus())
                .publicVisibilityRequested(requestDto.getPublicVisibilityRequested())
                .createdAt(requestDto.getCreatedAt())
                .updatedAt(requestDto.getUpdatedAt())
                .reviewedAt(requestDto.getReviewedAt())
                .reviewComment(requestDto.getReviewComment())
                .reviewedBy(requestDto.getReviewedBy())
                .declineReason(requestDto.getDeclineReason())
                .approvalNotes(requestDto.getApprovalNotes())
                .processedBy(requestDto.getProcessedBy())
                .quoteSentAt(requestDto.getQuoteSentAt())
                .approvedAt(requestDto.getApprovedAt())
                .declinedAt(requestDto.getDeclinedAt())
                .paidAt(requestDto.getPaidAt())
                .activatedAt(requestDto.getActivatedAt())
                .quoteBaseFee(requestDto.getQuoteBaseFee())
                .quoteUserFee(requestDto.getQuoteUserFee())
                .quoteModuleFee(requestDto.getQuoteModuleFee())
                .quoteSetupFee(requestDto.getQuoteSetupFee())
                .quoteTotal(requestDto.getQuoteTotal())
                .quoteAssumptions(requestDto.getQuoteAssumptions())
                .quoteAxesSnapshot(requestDto.getQuoteAxesSnapshot())
                .organizationCreatedId(requestDto.getOrganizationCreatedId())
                .build();
    }
}
